### ISSUE TITLE
[Research] Настроить авторизацию через яндекс

### ISSUE THREAD

**Issue by wi1sp** [book-hub-umsp/bh-infrastructure#13]
необходимо настроить oauth api яндекса для авторизации в нашем приложении

- создать приложение 
- добавить меня @wi1sp (`wi1sp@yandex.ru`)
- проверить автоизацию через Postman или HTTPie

**Comment by Re3w** [comment]
нужен эндпоинт **redirect_uri** , те куда пользователь будет перенаправлен после регистрации.
на какой эндпоинт будет приниматься токен?

**Comment by Re3w** [comment]
https://oauth.yandex.ru/authorize?response_type=token&client_id=5d3bf1b9496842a582905796a7fbb79c

GET https://login.yandex.ru/info?
[& format=json | xml | jwt]
[& jwt_secret=<секретный ключ>]
[& oauth_token=<токе>]

Authorization: OAuth <OAuth-токен>
