### ISSUE TITLE
Add database docker file

### ISSUE THREAD

**Issue by wi1sp** [book-hub-umsp/bh-infrastructure#3]
необходимо создать `DockerFile` для `PostgreSQL` базы с схожими настроками как в [бекэнд compose файле](https://github.com/book-hub-umsp/bh-backend-main-api/blob/master/src/docker-compose.yml)

**Comment by APTEM3OTOB** [comment]
[Docker.zip](https://github.com/user-attachments/files/17326777/Docker.zip)
